apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: backup
type: Opaque
data:
  mm_webhook_url: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # Webhook URL của Mattermost base64
  db_user: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY # Tên user của username sql base64
  db_password: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ # Mật khẩu của user sql base64
